// neatGradients.js

export const NEAT_GRADIENTS = [
  {
    id: "default",
    name: "Mặc định (Deep Sea)",
    cssBackground: "linear-gradient(135deg, #0F2027, #2C5364)",
    config: {
      colors: [
        { color: "#0F2027", enabled: true },
        { color: "#203A43", enabled: true },
        { color: "#2C5364", enabled: true },
        { color: "#182848", enabled: true },
        { color: "#4b6cb7", enabled: true },
      ],
      speed: 3,
      horizontalPressure: 4,
      verticalPressure: 5,
      waveFrequencyX: 2,
      waveFrequencyY: 3,
      waveAmplitude: 6,
      shadows: 0,
      highlights: 4,
      colorBrightness: 1,
      colorSaturation: 3,
      wireframe: false,
      colorBlending: 6,
      backgroundColor: "#000000",
      backgroundAlpha: 1,
      grainScale: 2,
      grainIntensity: 0.2,
      grainSpeed: 0.5,
      resolution: 0.5,
    },
  },
  {
    id: "colorful_party",
    name: "Lễ Hội Sắc Màu",
    cssBackground: "linear-gradient(135deg, #FF5772, #FFC600, #2E0EC7)",
    config: {
      colors: [
        { color: "#FF5772", enabled: true },
        { color: "#4CB4BB", enabled: true },
        { color: "#FFC600", enabled: true },
        { color: "#8B6AE6", enabled: true },
        { color: "#2E0EC7", enabled: true },
      ],
      speed: 2.5,
      horizontalPressure: 3,
      verticalPressure: 4,
      waveFrequencyX: 2,
      waveFrequencyY: 3,
      waveAmplitude: 5,
      shadows: 1,
      highlights: 5,
      colorBrightness: 1,
      colorSaturation: 7,
      wireframe: false,
      colorBlending: 8,
      backgroundColor: "#003FFF",
      backgroundAlpha: 1,
      grainScale: 0,
      grainSparsity: 0,
      grainIntensity: 0,
      grainSpeed: 1,
      resolution: 1,
      yOffset: 0,
    },
  },
  {
    id: "dark_abyss",
    name: "Vực Thẳm Đen",
    cssBackground: "linear-gradient(135deg, #000000, #001129)",
    config: {
      colors: [
        { color: "#000000", enabled: true },
        { color: "#001129", enabled: true },
        { color: "#0F0025", enabled: true },
        { color: "#14080A", enabled: true },
        { color: "#001129", enabled: true },
      ],
      speed: 2,
      horizontalPressure: 4,
      verticalPressure: 4,
      waveFrequencyX: 3,
      waveFrequencyY: 2,
      waveAmplitude: 1,
      shadows: 2,
      highlights: 2,
      colorBrightness: 1,
      colorSaturation: -1,
      wireframe: false,
      colorBlending: 7,
      backgroundColor: "#010101",
      backgroundAlpha: 1,
      grainScale: 2,
      grainSparsity: 0,
      grainIntensity: 0,
      grainSpeed: 1,
      resolution: 0.75,
      yOffset: 0,
    },
  },
  {
    id: "neon_flux",
    name: "Dòng Chảy Neon",
    cssBackground: "linear-gradient(135deg, #130437, #B34BD0)",
    config: {
      colors: [
        { color: "#130437", enabled: true },
        { color: "#B34BD0", enabled: true },
        { color: "#210751", enabled: true },
        { color: "#3511A5", enabled: true },
        { color: "#8F3E8D", enabled: false },
      ],
      speed: 4,
      horizontalPressure: 7,
      verticalPressure: 3,
      waveFrequencyX: 0,
      waveFrequencyY: 0,
      waveAmplitude: 0,
      shadows: 4,
      highlights: 0,
      colorBrightness: 1.95,
      colorSaturation: 2,
      wireframe: false,
      colorBlending: 9,
      backgroundColor: "#003FFF",
      backgroundAlpha: 1,
      grainScale: 0,
      grainSparsity: 0,
      grainIntensity: 0,
      grainSpeed: 0,
      resolution: 1,
      yOffset: 0,
    },
  },
  {
    id: "noir_film",
    name: "Trắng Đen (Noir)",
    cssBackground: "linear-gradient(135deg, #000000, #6D6464)",
    config: {
      colors: [
        { color: "#000000", enabled: true },
        { color: "#000000", enabled: true },
        { color: "#111212", enabled: true },
        { color: "#6D6464", enabled: true },
        { color: "#090A0A", enabled: true },
      ],
      speed: 2,
      horizontalPressure: 4,
      verticalPressure: 5,
      waveFrequencyX: 4,
      waveFrequencyY: 3,
      waveAmplitude: 2,
      shadows: 4,
      highlights: 7,
      colorBrightness: 1,
      colorSaturation: 0,
      wireframe: false,
      colorBlending: 7,
      backgroundColor: "#00A2FF",
      backgroundAlpha: 1,
      grainScale: 100,
      grainSparsity: 0,
      grainIntensity: 0.05,
      grainSpeed: 0.3,
      resolution: 0.5,
      yOffset: 0,
    },
  },
  // --- MỚI THÊM ---
  {
    id: "pine_forest",
    name: "Rừng Thông",
    cssBackground: "linear-gradient(135deg, #2A4235, #769E7A)",
    config: {
      colors: [
        { color: "#2A4235", enabled: true },
        { color: "#769E7A", enabled: true },
        { color: "#B2C9AB", enabled: true },
        { color: "#E5E5E5", enabled: true },
        { color: "#C4DDC5", enabled: false },
      ],
      speed: 2,
      horizontalPressure: 5,
      verticalPressure: 5,
      waveFrequencyX: 3,
      waveFrequencyY: 3,
      waveAmplitude: 4,
      shadows: 4,
      highlights: 6,
      colorBrightness: 1,
      colorSaturation: 5,
      wireframe: false,
      colorBlending: 8,
      backgroundColor: "#3B7D1E",
      backgroundAlpha: 1,
      grainScale: 2,
      grainSparsity: 0,
      grainIntensity: 0.2,
      grainSpeed: 0.8,
      resolution: 1.2,
      yOffset: 0,
    },
  },
];
