import { useContext } from "react";

// Import ThemeContext từ ThemeProvider
import { ThemeContext } from "./ThemeProvider";

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error("useTheme must be used within a ThemeProvider");
  }
  return context;
};

// Định nghĩa các theme
export const themes = {
  ocean: {
    id: "ocean",
    name: "Đại dương ngáo ngơ",
    emoji: "🐠",
    description: "Chủ đề biển cả với cá và san hô",
    colors: {
      primary: "teal",
      secondary: "emerald",
      accent: "cyan",
      background: "from-teal-900 via-teal-800 to-teal-700",
      backgroundOverlay: "from-teal-900/50 via-teal-800/50 to-teal-700/50",
      card: "teal-900/30",
      cardHover: "teal-800/50",
      text: "teal-300",
      textHover: "emerald-300",
      button: "teal-300/70",
      buttonHover: "emerald-400/70",
      border: "teal-700/30",
      gradient: "from-teal-400 to-emerald-400",
      // Song component colors
      songCard: "teal-900/30",
      songCardHover: "teal-800/50",
      songBorder: "teal-700/30",
      songBorderHover: "teal-400/20",
      songText: "white",
      songTextHover: "teal-200",
      songTextCurrent: "emerald-400",
      songArtist: "teal-300",
      songArtistHover: "emerald-400",
      songPlayCount: "teal-300",
      songPlayCountHover: "emerald-300",
      songButton: "teal-300/70",
      songButtonHover: "emerald-400/70",
      songButtonText: "teal-900",
      songShadow: "teal-500/25",
      songShadowHover: "teal-500/40",
      songRing: "teal-400/30",
      songOverlay: "from-teal-500/15 via-transparent to-teal-900/15",
      songIndicator: "teal-300",
    },
    backgroundImage:
      "https://yzfbdwvbybecxhbitkmc.supabase.co/storage/v1/object/sign/image/abcccccc.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV82OTc4ZGU2My0wOWQzLTRhYmYtOWRjZC0wZjY0NTBlN2VlYmIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZS9hYmNjY2NjYy5wbmciLCJpYXQiOjE3NTQxNDcxMjIsImV4cCI6MjA2OTUwNzEyMn0.pYqd1AjFr3DqSxnf0CiQoq1eKpFiIPSPH_ooRlSpIyI",
    particles: ["🫧", "🫧", "🫧", "🫧", "🫧", "🫧", "🫧", "🫧"],
  },
  forest: {
    id: "forest",
    name: "Rừng bí ẩn mà hổng bí",
    emoji: "🌲",
    description: "Chủ đề rừng xanh với thiên nhiên",
    colors: {
      primary: "green",
      secondary: "amber",
      accent: "emerald",
      background: "from-green-900 via-green-800 to-emerald-700",
      backgroundOverlay: "from-green-900/50 via-green-800/50 to-emerald-700/50",
      card: "green-900/30",
      cardHover: "green-800/50",
      text: "green-300",
      textHover: "amber-300",
      button: "amber-400/80",
      buttonHover: "amber-300/90",
      border: "amber-600/40",
      gradient: "from-green-400 to-amber-400",
      // Song component colors - Enhanced với gradient và hiệu ứng
      songCard: "green-900/30",
      songCardHover: "green-800/40",
      songBorder: "amber-500/50",
      songBorderHover: "amber-400/60",
      songText: "white",
      songTextHover: "green-200",
      songTextCurrent: "amber-300",
      songArtist: "green-300",
      songArtistHover: "amber-300",
      songPlayCount: "green-300",
      songPlayCountHover: "amber-300",
      // Enhanced button với gradient
      songButton: "gradient-to-r from-green-600 to-lime-500",
      songButtonHover: "gradient-to-r from-green-500 to-lime-400",
      songButtonText: "white",
      songShadow: "green-500/30",
      songShadowHover: "green-400/50",
      songRing: "amber-400/40",
      songOverlay: "from-amber-500/10 via-transparent to-green-900/10",
      songIndicator: "amber-400",
    },
    backgroundImage:
      "https://yzfbdwvbybecxhbitkmc.supabase.co/storage/v1/object/sign/image/tree.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV82OTc4ZGU2My0wOWQzLTRhYmYtOWRjZC0wZjY0NTBlN2VlYmIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZS90cmVlLnBuZyIsImlhdCI6MTc1NDIyMTk5MSwiZXhwIjoyMDY5NTgxOTkxfQ.k13CATHRnBrBYUMqG7MkJnssITIB-oVveoNxZ7-TLrA",
    particles: ["🌲", "🍃", "🦋", "🐛", "🌿"],
  },
  space: {
    id: "space",
    name: "Vũ trụ bao laaaaaa",
    emoji: "🌌",
    description: "Chủ đề vũ trụ với sao và hành tinh",
    colors: {
      primary: "purple",
      secondary: "pink",
      accent: "indigo",
      background: "from-purple-900 via-purple-800 to-indigo-700",
      backgroundOverlay:
        "from-purple-900/50 via-purple-800/50 to-indigo-700/50",
      card: "purple-900/30",
      cardHover: "purple-800/50",
      text: "purple-300",
      textHover: "pink-300",
      button: "purple-300/70",
      buttonHover: "pink-400/70",
      border: "purple-700/30",
      gradient: "from-purple-400 to-pink-400",
      // Song component colors - Enhanced với cosmic gradient
      songCard: "purple-900/30",
      songCardHover: "purple-800/50",
      songBorder: "purple-700/30",
      songBorderHover: "purple-400/20",
      songText: "white",
      songTextHover: "purple-200",
      songTextCurrent: "pink-400",
      songArtist: "purple-300",
      songArtistHover: "pink-400",
      songPlayCount: "purple-300",
      songPlayCountHover: "pink-300",
      // Enhanced button với cosmic gradient
      songButton: "gradient-to-r from-purple-600 to-violet-500",
      songButtonHover: "gradient-to-r from-indigo-600 to-purple-500",
      songButtonText: "white",
      songShadow: "purple-500/25",
      songShadowHover: "purple-500/40",
      songRing: "purple-400/30",
      songOverlay: "from-purple-500/15 via-transparent to-purple-900/15",
      songIndicator: "purple-300",
    },
    backgroundImage:
      "https://yzfbdwvbybecxhbitkmc.supabase.co/storage/v1/object/sign/image/purple.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV82OTc4ZGU2My0wOWQzLTRhYmYtOWRjZC0wZjY0NTBlN2VlYmIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZS9wdXJwbGUuanBlZyIsImlhdCI6MTc1NDIyMjM3NCwiZXhwIjoyMDY5NTgyMzc0fQ.ELBBsGxStjsfkU7a6sqUMVQNJVJde-Ft7m0nNjnv_ig",
    particles: ["⭐", "🌟", "✨", "🌙", "🪐"],
  },
  sunset: {
    id: "sunset",
    name: "Hoàng hôn siêu chillll =))",
    emoji: "🌅",
    description: "Chủ đề hoàng hôn ấm áp",
    colors: {
      primary: "orange",
      secondary: "amber",
      accent: "red",
      background: "from-orange-900 via-red-800 to-yellow-700",
      backgroundOverlay: "from-orange-900/50 via-red-800/50 to-yellow-700/50",
      card: "orange-900/30",
      cardHover: "orange-800/50",
      text: "orange-300",
      textHover: "amber-300",
      button: "orange-300/70",
      buttonHover: "amber-400/70",
      border: "orange-700/30",
      gradient: "from-orange-400 to-amber-400",
      // Song component colors - Enhanced với sunset gradient
      songCard: "orange-900/30",
      songCardHover: "orange-800/50",
      songBorder: "orange-700/30",
      songBorderHover: "orange-400/20",
      songText: "white",
      songTextHover: "orange-200",
      songTextCurrent: "amber-400",
      songArtist: "orange-300",
      songArtistHover: "amber-400",
      songPlayCount: "orange-300",
      songPlayCountHover: "amber-300",
      // Enhanced button với sunset gradient
      songButton: "gradient-to-r from-orange-600 to-amber-500",
      songButtonHover: "gradient-to-r from-red-500 to-orange-400",
      songButtonText: "white",
      songShadow: "orange-500/25",
      songShadowHover: "orange-500/40",
      songRing: "orange-400/30",
      songOverlay: "from-orange-500/15 via-transparent to-orange-900/15",
      songIndicator: "orange-300",
    },
    backgroundImage:
      "https://yzfbdwvbybecxhbitkmc.supabase.co/storage/v1/object/sign/image/Sunset_1754223838308.jpeg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV82OTc4ZGU2My0wOWQzLTRhYmYtOWRjZC0wZjY0NTBlN2VlYmIiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJpbWFnZS9TdW5zZXRfMTc1NDIyMzgzODMwOC5qcGVnIiwiaWF0IjoxNzU0MjIzOTY0LCJleHAiOjIwNjk1ODM5NjR9.vSAXjw3dhN3sbrlcfnBOV-MhGFM-VGuhvikNkTW5vHM",
    particles: ["🌅", "☀️", "🔥", "🍂", "🦋"],
  },
  // neon: {
  //   id: "neon",
  //   name: "Cyberpunk Neon",
  //   emoji: "⚡",
  //   description: "Chủ đề neon cyberpunk",
  //   colors: {
  //     primary: "cyan",
  //     secondary: "fuchsia",
  //     accent: "blue",
  //     background: "from-gray-900 via-blue-900 to-purple-900",
  //     backgroundOverlay: "from-gray-900/50 via-blue-900/50 to-purple-900/50",
  //     card: "gray-900/30",
  //     cardHover: "blue-900/50",
  //     text: "cyan-300",
  //     textHover: "fuchsia-300",
  //     button: "cyan-300/70",
  //     buttonHover: "fuchsia-400/70",
  //     border: "cyan-700/30",
  //     gradient: "from-cyan-400 to-fuchsia-400",
  //     // Song component colors
  //     songCard: "gray-900/30",
  //     songCardHover: "blue-900/50",
  //     songBorder: "cyan-700/30",
  //     songBorderHover: "cyan-400/20",
  //     songText: "white",
  //     songTextHover: "cyan-200",
  //     songTextCurrent: "fuchsia-400",
  //     songArtist: "cyan-300",
  //     songArtistHover: "fuchsia-400",
  //     songPlayCount: "cyan-300",
  //     songPlayCountHover: "fuchsia-300",
  //     songButton: "cyan-300/70",
  //     songButtonHover: "fuchsia-400/70",
  //     songButtonText: "gray-900",
  //     songShadow: "cyan-500/25",
  //     songShadowHover: "cyan-500/40",
  //     songRing: "cyan-400/30",
  //     songOverlay: "from-cyan-500/15 via-transparent to-blue-900/15",
  //     songIndicator: "cyan-300",
  //   },
  //   backgroundImage:
  //     "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=1920&h=1080&fit=crop",
  //   particles: ["⚡", "💫", "🔮", "💎", "🌈"],
  // },
};
